/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author usuario
 */
public class ADM_RegistrarProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ADM_Cubiculos1
     */
    public ADM_RegistrarProveedor() {
        initComponents();

        btnRetrocederAdmin.setContentAreaFilled(false);
        btnRetrocederAdmin.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetrocederAdmin = new javax.swing.JButton();
        txtnombreprov = new javax.swing.JTextField();
        txtcontactoprov = new javax.swing.JTextField();
        txtpaisprov = new javax.swing.JTextField();
        btnRegistrarProveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetrocederAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrocederAdmin.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnRetrocederAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button - Symbol.png"))); // NOI18N
        btnRetrocederAdmin.setBorderPainted(false);
        btnRetrocederAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrocederAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        txtnombreprov.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtnombreprov.setBorder(null);
        txtnombreprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreprovActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombreprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 210, 40));

        txtcontactoprov.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtcontactoprov.setBorder(null);
        txtcontactoprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactoprovActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontactoprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 210, 40));

        txtpaisprov.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtpaisprov.setBorder(null);
        txtpaisprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaisprovActionPerformed(evt);
            }
        });
        getContentPane().add(txtpaisprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 210, 40));

        btnRegistrarProveedor.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrarProveedor.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnRegistrarProveedor.setText("Registrar");
        btnRegistrarProveedor.setBorderPainted(false);
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/productos.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -40, 1440, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederAdminActionPerformed

    private void txtnombreprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreprovActionPerformed

    private void txtcontactoprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactoprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactoprovActionPerformed

    private void txtpaisprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaisprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaisprovActionPerformed

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarProveedor;
    public javax.swing.JButton btnRetrocederAdmin;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtcontactoprov;
    public javax.swing.JTextField txtnombreprov;
    public javax.swing.JTextField txtpaisprov;
    // End of variables declaration//GEN-END:variables
}
