/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author usuario
 */
public class ADM_ActualizarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ADM_Cubiculos1
     */
    public ADM_ActualizarProducto() {
        initComponents();

        btnRetrocederAdmin.setContentAreaFilled(false);
        btnRetrocederAdmin.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetrocederAdmin = new javax.swing.JButton();
        txtfechavencimientoprod = new javax.swing.JTextField();
        txtcodprov = new javax.swing.JTextField();
        txtnombreprod = new javax.swing.JTextField();
        btnActualizarProducto = new javax.swing.JButton();
        txtcodcategoria = new javax.swing.JTextField();
        txtprecioprod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetrocederAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrocederAdmin.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnRetrocederAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button - Symbol.png"))); // NOI18N
        btnRetrocederAdmin.setBorderPainted(false);
        btnRetrocederAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrocederAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        txtfechavencimientoprod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtfechavencimientoprod.setBorder(null);
        txtfechavencimientoprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechavencimientoprodActionPerformed(evt);
            }
        });
        getContentPane().add(txtfechavencimientoprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 210, 40));

        txtcodprov.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtcodprov.setBorder(null);
        txtcodprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodprovActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 210, 40));

        txtnombreprod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtnombreprod.setBorder(null);
        txtnombreprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreprodActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombreprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 210, 40));

        btnActualizarProducto.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizarProducto.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnActualizarProducto.setText("Actualizaar");
        btnActualizarProducto.setBorderPainted(false);
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 160, 40));

        txtcodcategoria.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtcodcategoria.setBorder(null);
        txtcodcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodcategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 210, 40));

        txtprecioprod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtprecioprod.setBorder(null);
        txtprecioprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioprodActionPerformed(evt);
            }
        });
        getContentPane().add(txtprecioprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GestionEmpresa.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -30, 1460, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederAdminActionPerformed

    private void txtfechavencimientoprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechavencimientoprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechavencimientoprodActionPerformed

    private void txtcodprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodprovActionPerformed

    private void txtnombreprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreprodActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void txtcodcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodcategoriaActionPerformed

    private void txtprecioprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioprodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarProducto;
    public javax.swing.JButton btnRetrocederAdmin;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtcodcategoria;
    public javax.swing.JTextField txtcodprov;
    public javax.swing.JTextField txtfechavencimientoprod;
    public javax.swing.JTextField txtnombreprod;
    public javax.swing.JTextField txtprecioprod;
    // End of variables declaration//GEN-END:variables
}
