/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Main.Principal;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.SwingUtilities;
/**
 *
 * @author Prueba
 */
public class Cliente_SVAD extends javax.swing.JInternalFrame {

    private JPanel panelContenedor;
    private JScrollBar jScrollBar;
    public Cliente_SVAD() {
        initComponents();
        btnpapah.setContentAreaFilled(false);
        btnensaladapalta.setContentAreaFilled(false);
        btnsopacasa.setContentAreaFilled(false);
        btntallarin.setContentAreaFilled(false);
        btnchicharron.setContentAreaFilled(false);
        btncaldomote.setContentAreaFilled(false);
        btncaldocabeza.setContentAreaFilled(false);
        btncaldogallina.setContentAreaFilled(false);
        btnchicha.setContentAreaFilled(false);
        btnincakola.setContentAreaFilled(false);
        btnmaracuya.setContentAreaFilled(false);
        btncocacola.setContentAreaFilled(false);
        btncafe.setContentAreaFilled(false);
        btnquequevainilla.setContentAreaFilled(false);
        btngelatinaflan.setContentAreaFilled(false);
        btngelatinafresa.setContentAreaFilled(false);
        btnquequenaranja.setContentAreaFilled(false);
        btnquequepiña.setContentAreaFilled(false);
        btnpagar.setContentAreaFilled(false);
        configurarBotonSpinner(btnpapah, spnpapah);
        configurarBotonSpinner(btnensaladapalta, spnensaladapalta);
        configurarBotonSpinner(btnsopacasa, spnsopacasa);
        configurarBotonSpinner(btntallarin, spntallarin);
        configurarBotonSpinner(btnchicharron, spnchicharron);
        configurarBotonSpinner(btncaldomote, spncaldomote);
        configurarBotonSpinner(btncaldocabeza, spncaldocabeza);
        configurarBotonSpinner(btncaldogallina, spncaldogallina);
        configurarBotonSpinner(btnchicha, spnchicha);
        configurarBotonSpinner(btnincakola, spnincakola);
        configurarBotonSpinner(btnmaracuya, spnmaracuya);
        configurarBotonSpinner(btncocacola, spncocacola);
        configurarBotonSpinner(btncafe, spncafe);
        configurarBotonSpinner(btnquequevainilla, spnquequevainilla);
        configurarBotonSpinner(btngelatinaflan, spngelatinaflan);
        configurarBotonSpinner(btngelatinafresa, spngelatinafresa);
        configurarBotonSpinner(btnquequenaranja, spnquequenaranja);
        configurarBotonSpinner(btnquequepiña, spnquequepiña);
    }
    private void configurarBotonSpinner(JButton boton, JSpinner spinner) {
    boton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Obtener el valor actual del JSpinner
            int valorActual = (int) spinner.getValue();
            // Incrementar el valor
            valorActual++;
            // Establecer el nuevo valor en el Spinner
            spinner.setValue(valorActual);
        }
    });
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnsopacasa = new javax.swing.JButton();
        btnpapah = new javax.swing.JButton();
        btntallarin = new javax.swing.JButton();
        btnchicharron = new javax.swing.JButton();
        btncaldomote = new javax.swing.JButton();
        btncaldocabeza = new javax.swing.JButton();
        btncaldogallina = new javax.swing.JButton();
        btnchicha = new javax.swing.JButton();
        btnincakola = new javax.swing.JButton();
        btnmaracuya = new javax.swing.JButton();
        btncocacola = new javax.swing.JButton();
        btncafe = new javax.swing.JButton();
        btngelatinafresa = new javax.swing.JButton();
        btnquequevainilla = new javax.swing.JButton();
        btngelatinaflan = new javax.swing.JButton();
        btnquequenaranja = new javax.swing.JButton();
        btnquequepiña = new javax.swing.JButton();
        btnensaladapalta = new javax.swing.JButton();
        spnensaladapalta = new javax.swing.JSpinner();
        spnsopacasa = new javax.swing.JSpinner();
        spntallarin = new javax.swing.JSpinner();
        spnchicharron = new javax.swing.JSpinner();
        spncaldomote = new javax.swing.JSpinner();
        spncaldocabeza = new javax.swing.JSpinner();
        spncaldogallina = new javax.swing.JSpinner();
        spnchicha = new javax.swing.JSpinner();
        spnincakola = new javax.swing.JSpinner();
        spnmaracuya = new javax.swing.JSpinner();
        spncocacola = new javax.swing.JSpinner();
        spncafe = new javax.swing.JSpinner();
        spnquequevainilla = new javax.swing.JSpinner();
        spngelatinaflan = new javax.swing.JSpinner();
        spngelatinafresa = new javax.swing.JSpinner();
        spnquequenaranja = new javax.swing.JSpinner();
        spnquequepiña = new javax.swing.JSpinner();
        spnpapah = new javax.swing.JSpinner();
        btnpagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();

        btnGuardarDatos.setBackground(new java.awt.Color(0, 204, 0));
        btnGuardarDatos.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnGuardarDatos.setText("SIGUIENTE");
        btnGuardarDatos.setBorderPainted(false);
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1331, 2560));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsopacasa.setBackground(new java.awt.Color(0, 204, 0));
        btnsopacasa.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnsopacasa.setForeground(new java.awt.Color(255, 255, 255));
        btnsopacasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnsopacasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnsopacasa.setBorderPainted(false);
        btnsopacasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsopacasaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsopacasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, 177, 53));

        btnpapah.setBackground(new java.awt.Color(0, 204, 0));
        btnpapah.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnpapah.setForeground(new java.awt.Color(255, 255, 255));
        btnpapah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnpapah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnpapah.setBorderPainted(false);
        btnpapah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpapahActionPerformed(evt);
            }
        });
        jPanel1.add(btnpapah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 177, 53));

        btntallarin.setBackground(new java.awt.Color(0, 204, 0));
        btntallarin.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btntallarin.setForeground(new java.awt.Color(255, 255, 255));
        btntallarin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btntallarin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btntallarin.setBorderPainted(false);
        btntallarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntallarinActionPerformed(evt);
            }
        });
        jPanel1.add(btntallarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1040, 177, 53));

        btnchicharron.setBackground(new java.awt.Color(0, 204, 0));
        btnchicharron.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnchicharron.setForeground(new java.awt.Color(255, 255, 255));
        btnchicharron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnchicharron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnchicharron.setBorderPainted(false);
        btnchicharron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchicharronActionPerformed(evt);
            }
        });
        jPanel1.add(btnchicharron, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1040, 177, 53));

        btncaldomote.setBackground(new java.awt.Color(0, 204, 0));
        btncaldomote.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btncaldomote.setForeground(new java.awt.Color(255, 255, 255));
        btncaldomote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btncaldomote.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncaldomote.setBorderPainted(false);
        btncaldomote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaldomoteActionPerformed(evt);
            }
        });
        jPanel1.add(btncaldomote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 1040, 177, 53));

        btncaldocabeza.setBackground(new java.awt.Color(0, 204, 0));
        btncaldocabeza.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btncaldocabeza.setForeground(new java.awt.Color(255, 255, 255));
        btncaldocabeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btncaldocabeza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncaldocabeza.setBorderPainted(false);
        btncaldocabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaldocabezaActionPerformed(evt);
            }
        });
        jPanel1.add(btncaldocabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1430, 177, 53));

        btncaldogallina.setBackground(new java.awt.Color(0, 204, 0));
        btncaldogallina.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btncaldogallina.setForeground(new java.awt.Color(255, 255, 255));
        btncaldogallina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btncaldogallina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncaldogallina.setBorderPainted(false);
        btncaldogallina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaldogallinaActionPerformed(evt);
            }
        });
        jPanel1.add(btncaldogallina, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 1430, 177, 53));

        btnchicha.setBackground(new java.awt.Color(0, 204, 0));
        btnchicha.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnchicha.setForeground(new java.awt.Color(255, 255, 255));
        btnchicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnchicha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnchicha.setBorderPainted(false);
        btnchicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchichaActionPerformed(evt);
            }
        });
        jPanel1.add(btnchicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2070, 177, 53));

        btnincakola.setBackground(new java.awt.Color(0, 204, 0));
        btnincakola.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnincakola.setForeground(new java.awt.Color(255, 255, 255));
        btnincakola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnincakola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnincakola.setBorderPainted(false);
        btnincakola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincakolaActionPerformed(evt);
            }
        });
        jPanel1.add(btnincakola, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 2070, 177, 53));

        btnmaracuya.setBackground(new java.awt.Color(0, 204, 0));
        btnmaracuya.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnmaracuya.setForeground(new java.awt.Color(255, 255, 255));
        btnmaracuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnmaracuya.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnmaracuya.setBorderPainted(false);
        btnmaracuya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaracuyaActionPerformed(evt);
            }
        });
        jPanel1.add(btnmaracuya, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 2070, 177, 53));

        btncocacola.setBackground(new java.awt.Color(0, 204, 0));
        btncocacola.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btncocacola.setForeground(new java.awt.Color(255, 255, 255));
        btncocacola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btncocacola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncocacola.setBorderPainted(false);
        btncocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncocacolaActionPerformed(evt);
            }
        });
        jPanel1.add(btncocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 2450, 177, 53));

        btncafe.setBackground(new java.awt.Color(0, 204, 0));
        btncafe.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btncafe.setForeground(new java.awt.Color(255, 255, 255));
        btncafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btncafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncafe.setBorderPainted(false);
        btncafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncafeActionPerformed(evt);
            }
        });
        jPanel1.add(btncafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 2450, 177, 53));

        btngelatinafresa.setBackground(new java.awt.Color(0, 204, 0));
        btngelatinafresa.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btngelatinafresa.setForeground(new java.awt.Color(255, 255, 255));
        btngelatinafresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btngelatinafresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btngelatinafresa.setBorderPainted(false);
        btngelatinafresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngelatinafresaActionPerformed(evt);
            }
        });
        jPanel1.add(btngelatinafresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 3090, 177, 53));

        btnquequevainilla.setBackground(new java.awt.Color(0, 204, 0));
        btnquequevainilla.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnquequevainilla.setForeground(new java.awt.Color(255, 255, 255));
        btnquequevainilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnquequevainilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnquequevainilla.setBorderPainted(false);
        btnquequevainilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquequevainillaActionPerformed(evt);
            }
        });
        jPanel1.add(btnquequevainilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 3090, 177, 53));

        btngelatinaflan.setBackground(new java.awt.Color(0, 204, 0));
        btngelatinaflan.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btngelatinaflan.setForeground(new java.awt.Color(255, 255, 255));
        btngelatinaflan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btngelatinaflan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btngelatinaflan.setBorderPainted(false);
        btngelatinaflan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngelatinaflanActionPerformed(evt);
            }
        });
        jPanel1.add(btngelatinaflan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 3090, 177, 53));

        btnquequenaranja.setBackground(new java.awt.Color(0, 204, 0));
        btnquequenaranja.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnquequenaranja.setForeground(new java.awt.Color(255, 255, 255));
        btnquequenaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnquequenaranja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnquequenaranja.setBorderPainted(false);
        btnquequenaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquequenaranjaActionPerformed(evt);
            }
        });
        jPanel1.add(btnquequenaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 3480, 177, 53));

        btnquequepiña.setBackground(new java.awt.Color(0, 204, 0));
        btnquequepiña.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnquequepiña.setForeground(new java.awt.Color(255, 255, 255));
        btnquequepiña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnquequepiña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnquequepiña.setBorderPainted(false);
        btnquequepiña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquequepiñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnquequepiña, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 3480, 177, 53));

        btnensaladapalta.setBackground(new java.awt.Color(0, 204, 0));
        btnensaladapalta.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnensaladapalta.setForeground(new java.awt.Color(255, 255, 255));
        btnensaladapalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botoncomprar.png"))); // NOI18N
        btnensaladapalta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnensaladapalta.setBorderPainted(false);
        btnensaladapalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnensaladapaltaActionPerformed(evt);
            }
        });
        jPanel1.add(btnensaladapalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 177, 53));
        jPanel1.add(spnensaladapalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 70, 40));
        jPanel1.add(spnsopacasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 370, 70, 40));
        jPanel1.add(spntallarin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 990, 50, 40));
        jPanel1.add(spnchicharron, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 990, 70, 40));
        jPanel1.add(spncaldomote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 990, 70, 40));
        jPanel1.add(spncaldocabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1370, 70, 40));
        jPanel1.add(spncaldogallina, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 1380, 70, 40));
        jPanel1.add(spnchicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 2020, 70, 40));
        jPanel1.add(spnincakola, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 2020, 70, 40));
        jPanel1.add(spnmaracuya, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 2020, 70, 40));
        jPanel1.add(spncocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2400, 70, 40));
        jPanel1.add(spncafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 2400, 70, 40));
        jPanel1.add(spnquequevainilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 3040, 70, 40));
        jPanel1.add(spngelatinaflan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3040, 70, 40));
        jPanel1.add(spngelatinafresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 3040, 70, 40));
        jPanel1.add(spnquequenaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 3420, 70, 40));
        jPanel1.add(spnquequepiña, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 3420, 70, 40));
        jPanel1.add(spnpapah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 368, 70, 40));

        btnpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonpagar.png"))); // NOI18N
        jPanel1.add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 279, 59));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carta.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1300, -1));

        jScrollPane1.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 620));
        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed

    }//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnsopacasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsopacasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsopacasaActionPerformed

    private void btnpapahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpapahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpapahActionPerformed

    private void btntallarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntallarinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntallarinActionPerformed

    private void btnchicharronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchicharronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchicharronActionPerformed

    private void btncaldomoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaldomoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncaldomoteActionPerformed

    private void btncaldocabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaldocabezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncaldocabezaActionPerformed

    private void btncaldogallinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaldogallinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncaldogallinaActionPerformed

    private void btnchichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchichaActionPerformed

    private void btnincakolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincakolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnincakolaActionPerformed

    private void btnmaracuyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaracuyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmaracuyaActionPerformed

    private void btncocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncocacolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncocacolaActionPerformed

    private void btncafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncafeActionPerformed

    private void btngelatinafresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngelatinafresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngelatinafresaActionPerformed

    private void btnquequevainillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquequevainillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnquequevainillaActionPerformed

    private void btngelatinaflanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngelatinaflanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngelatinaflanActionPerformed

    private void btnquequenaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquequenaranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnquequenaranjaActionPerformed

    private void btnquequepiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquequepiñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnquequepiñaActionPerformed

    private void btnensaladapaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnensaladapaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnensaladapaltaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardarDatos;
    public javax.swing.JButton btncafe;
    public javax.swing.JButton btncaldocabeza;
    public javax.swing.JButton btncaldogallina;
    public javax.swing.JButton btncaldomote;
    public javax.swing.JButton btnchicha;
    public javax.swing.JButton btnchicharron;
    public javax.swing.JButton btncocacola;
    public javax.swing.JButton btnensaladapalta;
    public javax.swing.JButton btngelatinaflan;
    public javax.swing.JButton btngelatinafresa;
    public javax.swing.JButton btnincakola;
    public javax.swing.JButton btnmaracuya;
    public javax.swing.JButton btnpagar;
    public javax.swing.JButton btnpapah;
    public javax.swing.JButton btnquequenaranja;
    public javax.swing.JButton btnquequepiña;
    public javax.swing.JButton btnquequevainilla;
    public javax.swing.JButton btnsopacasa;
    public javax.swing.JButton btntallarin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner spncafe;
    public javax.swing.JSpinner spncaldocabeza;
    public javax.swing.JSpinner spncaldogallina;
    public javax.swing.JSpinner spncaldomote;
    public javax.swing.JSpinner spnchicha;
    public javax.swing.JSpinner spnchicharron;
    public javax.swing.JSpinner spncocacola;
    public javax.swing.JSpinner spnensaladapalta;
    public javax.swing.JSpinner spngelatinaflan;
    public javax.swing.JSpinner spngelatinafresa;
    public javax.swing.JSpinner spnincakola;
    public javax.swing.JSpinner spnmaracuya;
    public javax.swing.JSpinner spnpapah;
    public javax.swing.JSpinner spnquequenaranja;
    public javax.swing.JSpinner spnquequepiña;
    public javax.swing.JSpinner spnquequevainilla;
    public javax.swing.JSpinner spnsopacasa;
    public javax.swing.JSpinner spntallarin;
    // End of variables declaration//GEN-END:variables
}
