/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author Prueba
 */
public class EscMetodosPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pedidos
     */
    public EscMetodosPago() {
        initComponents();
        btnRetrocederAdmin.setContentAreaFilled(false);
        btnRetrocederAdmin.setBorder(null);

        //txtUsuarioAdm.setBackground(new java.awt.Color(0,0,0,1));
        //txtContraseñaAdm.setBackground(new java.awt.Color(0,0,0,1));
        //btnIngresarAdm.putClientProperty("JButton.buttonType", "roundRect" );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetrocederAdmin = new javax.swing.JButton();
        dspEscritorio = new javax.swing.JDesktopPane();
        btnVisa = new javax.swing.JButton();
        btnYape = new javax.swing.JButton();
        btnPlin = new javax.swing.JButton();
        btnPagoEfectivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetrocederAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrocederAdmin.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnRetrocederAdmin.setBorderPainted(false);
        btnRetrocederAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrocederAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 50));

        dspEscritorio.setBackground(new java.awt.Color(51, 0, 0));
        dspEscritorio.setForeground(new java.awt.Color(102, 0, 51));
        getContentPane().add(dspEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1320, 490));

        btnVisa.setBackground(new java.awt.Color(255, 255, 255));
        btnVisa.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Visa.png"))); // NOI18N
        btnVisa.setBorderPainted(false);
        btnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 90, 80));

        btnYape.setBackground(new java.awt.Color(255, 255, 255));
        btnYape.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnYape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Yape.png"))); // NOI18N
        btnYape.setBorderPainted(false);
        btnYape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYapeActionPerformed(evt);
            }
        });
        getContentPane().add(btnYape, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 90, 80));

        btnPlin.setBackground(new java.awt.Color(255, 255, 255));
        btnPlin.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnPlin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Plin.png"))); // NOI18N
        btnPlin.setBorderPainted(false);
        btnPlin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlinActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 90, 80));

        btnPagoEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        btnPagoEfectivo.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnPagoEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PagoEfectivo.png"))); // NOI18N
        btnPagoEfectivo.setBorderPainted(false);
        btnPagoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoEfectivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Encabezadopago.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederAdminActionPerformed

    private void btnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisaActionPerformed

    private void btnYapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYapeActionPerformed

    private void btnPlinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlinActionPerformed

    private void btnPagoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagoEfectivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPagoEfectivo;
    public javax.swing.JButton btnPlin;
    public javax.swing.JButton btnRetrocederAdmin;
    public javax.swing.JButton btnVisa;
    public javax.swing.JButton btnYape;
    public javax.swing.JDesktopPane dspEscritorio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
