/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author usuario
 */
public class IngresoAdministrador extends javax.swing.JInternalFrame {

    public IngresoAdministrador() {
        initComponents();
        btnRetrocederAdm.setContentAreaFilled(false);
        txtUsuarioAdm.setBackground(new java.awt.Color(0,0,0,1));
        txtContraseñaAdm.setBackground(new java.awt.Color(0,0,0,1));
        btnIngresarAdm.putClientProperty("JButton.buttonType", "roundRect" );
        configurarTextosIngresoAdmin();
    }
    public void BorrarBordesIngresoAdmin() {
        txtUsuarioAdm.setBorder(null);
        txtContraseñaAdm.setBorder(null);
    }
    public void configurarTextosIngresoAdmin() {
        txtUsuarioAdm.setText("Usuario"); // Establece el texto inicial
        txtContraseñaAdm.setText("Contraseña");
        txtUsuarioAdm.setForeground(Color.LIGHT_GRAY); // Establece el color de texto en gris
        txtContraseñaAdm.setForeground(Color.LIGHT_GRAY);
        // Agrega un FocusListener para el campo usuario
        txtUsuarioAdm.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando el campo obtiene el foco, borra el texto y cambia el color del texto a negro
                if (txtUsuarioAdm.getText().equals("Usuario")) {
                    txtUsuarioAdm.setText("");
                    txtUsuarioAdm.setForeground(Color.WHITE);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando el campo pierde el foco y está vacío, vuelve a mostrar "usuario" en gris
                if (txtUsuarioAdm.getText().isEmpty()) {
                    txtUsuarioAdm.setText("Usuario");
                    txtUsuarioAdm.setForeground(Color.LIGHT_GRAY);
                }
            }
        });
        //contraseña
        txtContraseñaAdm.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando el campo obtiene el foco, borra el texto y cambia el color del texto a negro
                if (txtContraseñaAdm.getText().equals("Contraseña")) {
                    txtContraseñaAdm.setText("");
                    txtContraseñaAdm.setForeground(Color.WHITE);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando el campo pierde el foco y está vacío, vuelve a mostrar "contraseña" en gris
                if (txtContraseñaAdm.getText().isEmpty()) {
                    txtContraseñaAdm.setText("Contraseña");
                    txtContraseñaAdm.setForeground(Color.LIGHT_GRAY);
                }
            }
            
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetrocederAdm = new javax.swing.JButton();
        txtUsuarioAdm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtContraseñaAdm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnIngresarAdm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetrocederAdm.setBackground(new java.awt.Color(255, 255, 255));
        btnRetrocederAdm.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnRetrocederAdm.setBorderPainted(false);
        btnRetrocederAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederAdmActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrocederAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 60));

        txtUsuarioAdm.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtUsuarioAdm.setBorder(null);
        getContentPane().add(txtUsuarioAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 340, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 30, 30));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("___________________________________________________________________");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        txtContraseñaAdm.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        getContentPane().add(txtContraseñaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 340, 40));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("___________________________________________________________________");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        btnIngresarAdm.setBackground(new java.awt.Color(255, 0, 0));
        btnIngresarAdm.setFont(new java.awt.Font("Monospac821 BT", 0, 24)); // NOI18N
        btnIngresarAdm.setText("Ingresar");
        btnIngresarAdm.setBorderPainted(false);
        btnIngresarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAdmActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 330, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetrocederAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetrocederAdmActionPerformed

    private void btnIngresarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAdmActionPerformed

    }//GEN-LAST:event_btnIngresarAdmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresarAdm;
    public javax.swing.JButton btnRetrocederAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtContraseñaAdm;
    public javax.swing.JTextField txtUsuarioAdm;
    // End of variables declaration//GEN-END:variables

}
