/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author usuario
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelprin = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CLT_Cubiculos = new javax.swing.JMenuItem();
        CLT_SVAD = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ADM_Cubiculos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("CLIENTE");

        CLT_Cubiculos.setText("Cubiculos");
        CLT_Cubiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLT_CubiculosActionPerformed(evt);
            }
        });
        jMenu1.add(CLT_Cubiculos);

        CLT_SVAD.setText("Servicios Adicionales");
        CLT_SVAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLT_SVADActionPerformed(evt);
            }
        });
        jMenu1.add(CLT_SVAD);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("ADMINISTRADOR");

        ADM_Cubiculos.setText("Gestion Cubiculos");
        ADM_Cubiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADM_CubiculosActionPerformed(evt);
            }
        });
        jMenu2.add(ADM_Cubiculos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panelprin, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panelprin, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLT_CubiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLT_CubiculosActionPerformed


    }//GEN-LAST:event_CLT_CubiculosActionPerformed

    private void CLT_SVADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLT_SVADActionPerformed
    
    }//GEN-LAST:event_CLT_SVADActionPerformed

    private void ADM_CubiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADM_CubiculosActionPerformed

    }//GEN-LAST:event_ADM_CubiculosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ADM_Cubiculos;
    public javax.swing.JMenuItem CLT_Cubiculos;
    public javax.swing.JMenuItem CLT_SVAD;
    public javax.swing.JPanel Panelprin;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
